### ISSUE TITLE
service.electron.build is unavailable

### ISSUE THREAD

**Issue by mankey-ru** [electron-userland/electron-build-service#5]
Trying to build an app for Linux on Windows machine with this result:
![2019-01-11 13_18_10-is service electron build down_](https://user-images.githubusercontent.com/13963043/51032121-e2338c80-15af-11e9-96e6-bce1b43840ea.png)

![2019-01-11 13_18_25-](https://user-images.githubusercontent.com/13963043/51032126-e8296d80-15af-11e9-9ded-e6f65ca4f31f.png)

Thanks in advance

**Comment by dextronox** [comment]
Yep, same issue.

**Comment by blue00** [comment]
Same issue (Building electron-app for Linux on Windows machine).
electron-builder version=20.36.2

**Comment by hodn** [comment]
I tried to build AppImage from Windows. The server is still down.

**Comment by AndreD23** [comment]
Tried today. Still down.

**Comment by develar** [comment]
Started to work on, https://github.com/electron-userland/electron-build-service/commit/db21f28e7f235cc8b0e8aee2e60d46a343de38b7 I hope it will deployed again soon.

**Comment by develar** [comment]
Comment from @eatmyvenom  caught me when I returned from the Snapcraft Summit, so... thanks to Canonical, now build service is deployed again.

Build capacity is not so wide as before, but I am sure that it will be enough and build queue time will be acceptable.

Please note, that electron-builder 20.44.2 is recommended to use a new build service version.

**Comment by Prathyushamadabhushi** [comment]
Is there a way to cache electron builder, I am trying to install it offline but always stops at Get https://github.com/electron-userland/electron-builder-binaries/releases/download/fpm-1.9.3-2.3.1-linux-x86_64/fpm-1.9.3-2.3.1-linux-x86_64.7z: dial tcp: lookup github.com on 127.0.0.53:53: server misbehaving

I did ELECTRON_BUILD_CACHE="~/.cache/electron-builder"

**Comment by develar** [comment]
@Prathyushamadabhushi See https://github.com/electron-userland/electron-builder/issues/3220#issuecomment-509609119

**Comment by john2515** [comment]
@develar we are facing the same issue while building .ext for windows

**Comment by suprimex** [comment]
Same issue (Building electron-app for Linux on Windows machine).

**Comment by oNexiaoyao** [comment]
Same issue too (Building electron-app for Linux on Windows machine).

**Comment by xctest** [comment]
Still Not Work (Building electron-app for Linux on Windows machine).
Any Help.......

**Comment by InfRandomness** [comment]
Same here, building for Linux from Windows

**Comment by githubfan** [comment]
Yea, can't build for Linux on Windows

**Comment by miyanoyuriko** [comment]
How to  build an electron-app for Linux on Windows?Please help me

**Comment by miyanoyuriko** [comment]
> Yea, can't build for Linux on Windows

HI,did you solve this problem?How did you buid for linux

**Comment by priyank780** [comment]
I'm getting an error while building Linux installer using Windows OS,

I'm using "electron-builder": "^21.0.15",

 cannot get, wait  error=Get https://service.electron.build/find-build-agent?no-cache=1fhqhpm: dial tcp xx.xx.xx.xxx:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
                      attempt=0
                      waitTime=2

**Comment by PauloRodrigues33** [comment]
2021, the problem persist here..

electron-builder: 22.9.1

**Comment by fomekh** [comment]
Same error  building Linux installer using Windows OS.
electron-builder: 22.10.5

**Comment by mmaietta** [comment]
AFAIK, this service is intentionally no longer running.
If so, it'd probably be best to update the README.md that the service is no longer maintained and users should utilize this repo as an example on how to set up their own service.

**Comment by oulshu** [comment]
Кто нибуль встречал такую ошибку и находил решение нее?
` dotnet electronize build /target linux /PublishSingleFile false /PublishReadyToRun false
Build Electron Application...
Build ASP.NET Core App for linux-x64...
Executing dotnet publish in this directory: S:\Code\TextTerminal\TextTerminal\obj\desktop\linux
Build ASP.NET Core App for linux-x64 under Release-Configuration...
Microsoft Windows [Version 10.0.19043.985]
(c) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.
S:\Code\TextTerminal\TextTerminal>dotnet publish -r linux-x64 -c "Release" --output "S:\Code\TextTerminal\TextTerminal\obj\desktop\linux\bin" /p:PublishReadyToRun=false /p:PublishSingleFile=false --self-contained
Microsoft (R) Build Engine версии 16.10.0-preview-21181-07+073022eb4 для .NET
(C) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.
  Определение проектов для восстановления...
  Все проекты обновлены для восстановления.
  Вы используете предварительную версию .NET. Дополнительные сведения см. на странице https://aka.ms/dotnet-core-preview.
  Terminal -> S:\Code\TextTerminal\TextTerminal\bin\Release\net5.0\linux-x64\Terminal.dll
  Terminal -> S:\Code\TextTerminal\TextTerminal\bin\Release\net5.0\linux-x64\Terminal.Views.dll
  Terminal -> S:\Code\TextTerminal\TextTerminal\obj\desktop\linux\bin\
S:\Code\TextTerminal\TextTerminal>
Start npm install...
Microsoft Windows [Version 10.0.19043.985]
(c) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.
S:\Code\TextTerminal\TextTerminal\obj\desktop\linux>npm install --production
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
added 68 packages, and audited 69 packages in 7s
found 0 vulnerabilities
S:\Code\TextTerminal\TextTerminal\obj\desktop\linux>
ElectronHostHook handling started...
Build Electron Desktop Application...
Executing electron magic in this directory: S:\Code\TextTerminal\TextTerminal\bin\desktop
Create electron-builder configuration file...
Microsoft Windows [Version 10.0.19043.985]
(c) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.
S:\Code\TextTerminal\TextTerminal\obj\desktop\linux>node build-helper.js electron.manifest.json
S:\Code\TextTerminal\TextTerminal\obj\desktop\linux>
Package Electron App for Platform linux...
Microsoft Windows [Version 10.0.19043.985]
(c) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.
S:\Code\TextTerminal\TextTerminal\obj\desktop\linux>npx electron-builder --config=./bin/electron-builder.json --linux --x64 -c.electronVersion=11.1.1
  тАв electron-builder  version=22.10.5 os=10.0.19043
  тАв loaded configuration  file=S:\Code\TextTerminal\TextTerminal\obj\desktop\linux\bin\electron-builder.json
  тАв description is missed in the package.json  appPackageFile=S:\Code\TextTerminal\TextTerminal\obj\desktop\linux\package.json
  тАв packaging       platform=linux arch=x64 electron=11.1.1 appOutDir=S:\Code\TextTerminal\TextTerminal\bin\Desktop\linux-unpacked
  тАв scheduling remote build  target=snap arch=x64
  тАв scheduling remote build  target=appImage arch=x64
  тАв cannot get, wait  error=Get "https://service.electron.build/find-build-agent?no-cache=1gamer5": dial tcp 51.15.76.176:443: connectex: No connection could be made because the target machine actively refused it.
                      attempt=0
                      waitTime=2
  тАв cannot get, wait  error=Get "https://service.electron.build/find-build-agent?no-cache=1gamer5": dial tcp 51.15.76.176:443: connectex: No connection could be made because the target machine actively refused it.
                      attempt=1
                      waitTime=4
  тАв cannot get, wait  error=Get "https://service.electron.build/find-build-agent?no-cache=1gamer5": dial tcp 51.15.76.176:443: connectex: No connection could be made because the target machine actively refused it.
                      attempt=2
                      waitTime=6
  тип Get "https://service.electron.build/find-build-agent?no-cache=1gamer5": dial tcp 51.15.76.176:443: connectex: No connection could be made because the target machine actively refused it.
  тип C:\Users\oulshu\AppData\Local\npm-cache\_npx\009083ec26dc578f\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace=

                                                        Error: C:\Users\oulshu\AppData\Local\npm-cache\_npx\009083ec26dc578f\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE

                                                            at ChildProcess.<anonymous> (C:\Users\oulshu\AppData\Local\npm-cache\_npx\009083ec26dc578f\node_modules\builder-util\src\util.ts:243:14)

                                                            at Object.onceWrapper (events.js:483:26)

                                                            at ChildProcess.emit (events.js:376:20)

                                                            at maybeClose (internal/child_process.js:1055:16)

                                                            at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)

                                                        From previous event:

                                                            at processImmediate (internal/timers.js:462:21)

                                                        From previous event:

                                                            at RemoteBuilder.build (C:\Users\oulshu\AppData\Local\npm-cache\_npx\009083ec26dc578f\node_modules\app-builder-lib\src\remoteBuilder\RemoteBuilder.ts:52:28)

                                                            at RemoteTarget.finishBuild (C:\Users\oulshu\AppData\Local\npm-cache\_npx\009083ec26dc578f\node_modules\app-builder-lib\src\linuxPackager.ts:99:30)

                                                            at async Promise.all (index 2)

                                                            at AsyncTaskManager.awaitTasks (C:\Users\oulshu\AppData\Local\npm-cache\_npx\009083ec26dc578f\node_modules\builder-util\src\asyncTaskManager.ts:65:25)

                                                            at Packager.doBuild (C:\Users\oulshu\AppData\Local\npm-cache\_npx\009083ec26dc578f\node_modules\app-builder-lib\src\packager.ts:446:5)

                                                            at executeFinally (C:\Users\oulshu\AppData\Local\npm-cache\_npx\009083ec26dc578f\node_modules\builder-util\src\promise.ts:12:14)

                                                            at Packager._build (C:\Users\oulshu\AppData\Local\npm-cache\_npx\009083ec26dc578f\node_modules\app-builder-lib\src\packager.ts:369:31)

                                                            at Packager.build (C:\Users\oulshu\AppData\Local\npm-cache\_npx\009083ec26dc578f\node_modules\app-builder-lib\src\packager.ts:333:12)

                                                            at executeFinally (C:\Users\oulshu\AppData\Local\npm-cache\_npx\009083ec26dc578f\node_modules\builder-util\src\promise.ts:12:14)`
